# Generated by Django 2.2 on 2022-05-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='items_known',
            new_name='dashboard_product',
        ),
    ]
