# Generated by Django 2.2 on 2022-05-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220503_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dashboard_product',
            new_name='Item',
        ),
    ]
